require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/coveralls/fixtures/**/*'
    - 'vendor/bundle/**/*'

Metrics/AbcSize:
  Max: 38.2

Metrics/CyclomaticComplexity:
  Max: 18

Metrics/PerceivedComplexity:
  Max: 19

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'lib/coveralls/configuration.rb'
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
